Add directory packages, use latest workflow part, add fossa ignore

diff --git a/.github/workflows/reusable-git-check.yml b/.github/workflows/reusable-git-check.yml
--- a/.github/workflows/reusable-git-check.yml
+++ b/.github/workflows/reusable-git-check.yml
@@ -23,7 +23,7 @@ jobs:
       - name: Clone repository
         uses: actions/checkout@v6
         with:
-          fetch-depth: 2
+          fetch-depth: 0
       - name: Debug git context
         if: ${{ inputs.debug }}
         run: |
@@ -33,10 +33,8 @@ jobs:
           git log --oneline -n 2 || echo "git log failed"
           echo ""
           echo "Quick diff summary:"
-          git diff --name-status ${{ github.event.before }} ${{ github.sha }} -- src/** 2>/dev/null \
-            || echo "No changes in src or diff failed"
-          git diff --name-status ${{ github.event.before }} ${{ github.sha }} -- test/** 2>/dev/null \
-            || echo "No changes in test or diff failed"
+          git diff --name-status ${{ github.event.before }} ${{ github.sha }} -- src test 2>/dev/null \
+            || echo "No changes in src test or diff failed"
       - name: Check git diff
         id: git-diff
         run: |
